### PR TITLE
Update smac.cfg defaults

### PR DESCRIPTION
**Pull request by Perkzitos**

### CODE REVIEW

**Comment by caxanga334** [comment]
This is pointless, the config file is auto-generated.

**Comment by Perkzitos** [comment]
> This is pointless, the config file is auto-generated.

I know that, but I am updating the file to possibly make the owner update the plugin to generate the new settings (if the new settings are approved).

**Comment by caxanga334** [comment]
The convar default value is defined in the plugin code, not the config file.
For example: https://github.com/Silenci0/SMAC/blob/master/addons/sourcemod/scripting/smac_aimbot.sp#L58

**Comment by Perkzitos** [comment]
> The convar default value is defined in the plugin code, not the config file.
> For example: https://github.com/Silenci0/SMAC/blob/master/addons/sourcemod/scripting/smac_aimbot.sp#L58

Thanks but, I know about this. That is why I have said:

> I know that, but I am updating the file to **possibly make the owner update the plugin to generate the new settings** (if the new settings are approved).

**Comment by MAGNAT2645** [comment]
You can't just replace 0.000000 with 0 (or 1.000000 with 1) because SourceMod accepts float numbers as ConVar bounds (min & max).
So auto-generated configs will always have float value as minimum or/and maximum.

**Pull request closed without merging**
