### PR TITLE
Updated To New Syntax

### PR DESCRIPTION
**Pull request by caxanga334**
* Updated all plugins to new syntax.
* Replaced colors with morecolors.

Note: Compiled on SM 1.10

### CODE REVIEW

**Comment by Silenci0** [comment]
Oh wow, thank you for this, its really appreciated! I'll be reviewing the changes made, which might take a little bit of time, and I'll get back to you on merging the files into the main repo.

**Comment by Silenci0** [comment]
Sorry for the wait on this, but after reviewing everything, I'll be merging this request and following it up with another update to the repo as well with some updates of my own shortly after.

As an aside, I'd like to mention that the code in the repo uses soft tabs instead of hard tabs with the soft tabs being 4 spaces == 1 tab. While I did not clearly outline this clearly for the repo (which is my fault for not doing so, I will correct this later with a general guideline), I wanted to mention it here for future updates/releases since it is important for the code to stay consistent.

However, do not take the above as criticism, I simply wanted to mention it for future updates/clarity. The code you've contributed works and is a vast improvement in modernizing SMAC overall, which is both great and very welcome for the project. Excellent work and thank you for your contribution!

**Comment by caxanga334** [comment]
> As an aside, I'd like to mention that the code in the repo uses soft tabs instead of hard tabs with the soft tabs being 4 spaces == 1 tab. While I did not clearly outline this clearly for the repo (which is my fault for not doing so, I will correct this later with a general guideline), I wanted to mention it here for future updates/releases since it is important for the code to stay consistent.

Soft tab gives warning 217: loose indentation

**Comment by Silenci0** [comment]
ah I see, that would explain it.

No worries. In the latest upload, I made sure to double check and retab the code. I did not get any errors or indentation warnings on my end so I think it should be okay now.

Again, thank you for your contribution!

**Pull request merged**
